export const REGISTER_SUCCESS = "REGISTER_ACCOUNT";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_ACCOUNT";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_ACCOUNT";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const AUTH_ERROR = "AUTH_ERROR";

export const VALIDATION_SUCCESS = "VALIDATION_SUCCESS"
export const VALIDATION_ERROR = "VALIDATION_ERROR"


export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
