export const REGISTER_SUCCESS = "REGISTER_ACCOUNT";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_ACCOUNT";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_ACCOUNT";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const AUTH_ERROR = "AUTH_ERROR";

export const VALIDATION_SUCCESS = "VALIDATION_SUCCESS";
export const VALIDATION_ERROR = "VALIDATION_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const FORGOT_PASSWORD="FORGOT_PASSWORD"
export const RESET_PASSWORD="RESET_PASSWORD"

//Programmes
export const LOADING_PROGRAMS = "LOADING_PROGRAMS"
export const LOADED_PROGRAMS = "LOADED_PROGRAMS"
export const BUDGET_AND_BENEFICIARIES = "BUDGET_AND_BENEFICIARIES"
export const GET_PROGRAMS = "GET_PROGRAMS"
export const PROGRAM_ERROR = "PROGRAM_ERROR"
export const GET_ALL_SDGS_INDICATORS = "GET_ALL_SDGS_INDICATORS"
export const GET_INDICATORS_UNDER_SDGS = "GET_INDICATORS_UNDER_SDGS"
export const CREATED_PROGRAM = "CREATE_PROGRAM"
export const FORM_REPORT_FOR_PROGRAM = "FORM_REPORT_FOR_PROGRAM"
export const CLEAR_REPORT = "CLEAR_REPORT"

//form Management
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS";
export const FORMS_SUCCESS = "FORMS_SUCCESS";
export const FORM_SUCCESS = "FORM_SUCCESS";
export const FORM_ERROR = "FORM_ERROR";
export const DELETE_FORM = "DELETE_FORM";
export const FORM_LOADING = "FORM_LOADING";
export const FILTER_FORM = "FILTER_FORM";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const PROGRAMS_SUCCESS= "PROGRAMS_SUCCESS"
export const INDICATOR_QUESTIONS_SUCCESS="INDICATOR_QUESTIONS_SUCCESS"
export const FORM_BUILD_ANSWER="FORM_BUILD_ANSWER"
export const CREATE_SUBMISSION_SUCCESS='CREATE_SUBMISSION_SUCCESS'

//profile
export const GET_PROFILE="GET_PROFILE"
export const PROFILE_LOADING="PROFILE_LOADING"
export const PROFILE_UPDATE="PROFILE_UPDATE"
export const PROFILE_ERROR="PROFILE_ERROR"


export const COMPONENT_TYPES = {
  number: 'number',
  radio: 'radio',
  text: 'text',
}